################################################################################
#
#	Makefile to build PyDAS benard example
#
################################################################################

all: 
	python setup.py build_ext --inplace

clean:
	python setup.py clean
	rm -rf *.so *.c *.html build
